export const engineeringJobs = [
    {
        company: 'TTI',
        position: 'Quality Management & Lab Interns',
        location: '',
        JD_link: 'https://drive.google.com/drive/folders/1d0fA8dUPPOkiGuE9ol4vdejSSlfpa-xr?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Value Engineering Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1ni3XKWrUyzND79IV6MeMp0-lcc89kiiV/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Project Engineer Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1pzmJgn0t51KwZ_FcKhtb9tOd7OD07UcZ/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Production Support Engineering Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1U8uPIKUguToutlF6LjiHSDehgC0CHOgH/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Process Engineering Engineer',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1qNqTSVPRbDR2z8_hYZCIuuFQRZe3byLd/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'New Product Development Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1oJuO8r213SR-D2Sl3DZmc2dohqjGNeEo/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Motor Engineering Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1wzSRIXzXUBwzrz9o_YHxcG05HXnvz_YT/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Equipment Engineering Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1GFq1jMiq1WPDRqLRBPjwIoGAZbzGEjVe/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Engineering Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/13NbZAat8W1ZsW0vG4lLV6-7l1daV-pAc/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Engineer of Motor Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1Yq2F_fPMrdoPK8tINX1CBHxCmncgcjZ0/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Electronics Engineer Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1HewW2Qp2Ke66-W-Ryi0FQup3a0ARD4-f/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'Nextern',
        position: 'IPQC Engineer',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1QYmQ8cEqH_PT1s5sPdPvxIJhJ8kKpoVH/view?usp=drive_link',
        logo: require('../../images/logo_2025/nextern.webp'),
    },
    {
        company: 'Wanek',
        position: 'Warehouse Automation Design Engineer',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1T1FQe2zEufYXK53lJongo5GYsU9yLjMk/edit',
        logo: require('../../images/logo_2025/wanek.webp'),
    },
    {
        company: 'Wanek',
        position: 'PLC & Robotic Programmer',
        location: '',
        JD_link: 'https://docs.google.com/document/d/17C9arb3CKXDTocXvXebWkOi7fLek0EyT/edit',
        logo: require('../../images/logo_2025/wanek.webp'),
    },
    {
        company: 'Wanek',
        position: 'Automation Design Engineer',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1woloLCZDy4LZhFm_FU0XTzKAb3ngjGar/edit?usp=drive_web&ouid=113519301845794276564&rtpof=true',
        logo: require('../../images/logo_2025/wanek.webp'),
    },
    {
        company: 'Indefol',
        position: 'Mechanical Engineer Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1Z7fnt3QDPDKp_twCJzedIN2CJuvhdnJD/view?usp=drive_open',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'Indefol',
        position: 'Quality Management Engineering Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1bosarfvCa9jp24t1QoUGgUeb0WsYnGDn/view?usp=drive_open',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'Indefol',
        position: 'Automation Electrical Engineer',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1-aW4L18vdTq8SJBBadB8XO-UpTrXqhwr/view?usp=drive_link',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'Indefol',
        position: 'Mechanical Engineer',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1uv50Wxt8ZwlP_lgD5VwZntwXVDBYz50N/view?usp=drive_link',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'Indefol',
        position: 'Quality Management Engineer',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1Y7eukgMP4R2rZM4PGyHvrnfpNbHECBV4/view?usp=drive_link',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'MAC ZT',
        position: 'MEP Engineer - HVAC Modeler',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1YcOw6Z6-rIKwMXyprdCDaA-_N8G__5O2/edit?usp=drive_link&ouid=107987931277148505499&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/MAC ZT.webp'),
    },
    {
        company: 'MAC ZT',
        position: 'MEP Engineer - Sanitary Modeler',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1YYwqy7RVgYGR4KhSMpPORM5Wa5Vb8YNw/view?usp=sharing',
        logo: require('../../images/logo_2025/MAC ZT.webp'),
    },
    {
        company: 'FPT Software',
        position: 'Fresher SAP Functional Consultant (German/French)',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1B-ijLygA_Of3dn5x4uHdJx133ZA2_r2L/edit?usp=drive_link&ouid=107987931277148505499&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/FPT Software.webp'),
    },
    {
        company: 'Ziel Abegg',
        position: 'HSE (Health, Safety, and Environment) Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1W5lvk2Mx3LKBPJVcyFcpLXfui5R428P4/view?usp=drive_link',
        logo: require('../../images/logo_2025/Ziehl Abegg.webp'),
    },
    {
        company: 'Ziel Abegg',
        position: 'Maintenance Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1L9_LPPHndMnc2CYZeKjIzXxDnRzPgT0u/view?usp=drive_link',
        logo: require('../../images/logo_2025/Ziehl Abegg.webp'),
    },
    {
        company: 'Ziel Abegg',
        position: 'Manufacturing Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1qXMIcettuR20J9qn3zkwALRVlC1YJrQQ/view?usp=drive_link',
        logo: require('../../images/logo_2025/Ziehl Abegg.webp'),
    },
  ];
  
  export const econMgmtJobs = [
    {
        datacompany: 'TTI',
        position: 'Translator-Interpreter Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1DHjVSQKeFfgc77IIYr4MrrORIlh4V5P3/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Supply Chain Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1VmU_7uJrV5sCu44CS6xWsMtqTvXF11k-/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Operation Compliance Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1AxRUCTAEDGX6Zd0QGnNCri8Npzp2iPmd/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'Shopee',
        position: 'Customer Relationship Management Associate - Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01995372/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'Shopee',
        position: 'Partnership Management Associate - SPX Express',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01995338/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'Shopee',
        position: 'Campaign Management Associate - Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01995168/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'Shopee',
        position: 'Business Product Management Associate - Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01995300/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'Shopee',
        position: 'Business Development Planning Associate - Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J02011945/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'Shopee',
        position: 'Ads Services Specialist',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J02012106/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'Shopee',
        position: 'Warehouse Admin - Operations, Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J00338971/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'Shopee',
        position: 'Quality Assurance Associate - Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01995273/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'Shopee',
        position: 'Key Account Management Associate - Shopee HCM',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01994668/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'Shopee',
        position: 'Key Account Management Associate - Shopee HN',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01994687/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'Shopee',
        position: 'BD Admin - Business Development, ShopeeFood',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J02012398/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'Shopee',
        position: 'Recruiter - People Team, Shopee (Working location: Ha Noi & Ho Chi Minh)',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J02007770/1?channel=10001',
        logo: require('../../images/logo_2025/Shopee Express.webp'),
    },
    {
        company: 'FPT Software',
        position: 'Fresher SAP Functional Consultant (German/French)',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1B-ijLygA_Of3dn5x4uHdJx133ZA2_r2L/edit?usp=drive_link&ouid=107987931277148505499&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/FPT Software.webp'),
    },
    {
        company: 'Ziel Abegg',
        position: 'Accountant Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1K5CS8MhVwerDDIGWn8vrA9sww43447Mz/view?usp=drive_link',
        logo: require('../../images/logo_2025/Ziehl Abegg.webp'),
    },
    {
        company: 'Ziel Abegg',
        position: 'HR - Admin Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1TVZUcsgRP5OCGYrNCcjRzPMc9EReMNDb/view?usp=drive_link',
        logo: require('../../images/logo_2025/Ziehl Abegg.webp'),
    },
  ];
  export const urbanEnvJobs = [
    {
        company: 'Mitek',
        position: 'Structural designer',
        location: '',
        JD_link: 'https://docs.google.com/spreadsheets/d/1hXNxizMhjSfS1u6keaFMc__xoRSNXFfD/edit?usp=drive_link&ouid=113519301845794276564&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/mitek.webp'),
    },
    {
        company: 'Mitek',
        position: 'Architectural Drafter',
        location: '',
        JD_link: 'https://docs.google.com/spreadsheets/d/1hXNxizMhjSfS1u6keaFMc__xoRSNXFfD/edit?usp=drive_link&ouid=113519301845794276564&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/mitek.webp'),
    },
    {
        company: 'Mitek',
        position: 'Budget Officer',
        location: '',
        JD_link: 'https://docs.google.com/spreadsheets/d/1hXNxizMhjSfS1u6keaFMc__xoRSNXFfD/edit?usp=drive_link&ouid=113519301845794276564&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/mitek.webp'),
    },
    {
        company: 'Indefol',
        position: 'Chemical Engineer Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1h4rRwc6mfyRUF7Vl9IBAAyZoHGRe6Pbo/view?usp=drive_open',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'FPT Software',
        position: 'Fresher SAP Functional Consultant (German/French)',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1B-ijLygA_Of3dn5x4uHdJx133ZA2_r2L/edit?usp=drive_link&ouid=107987931277148505499&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/FPT Software.webp'),
    },
  ];
  export const itJobs = [
    {
    company: 'Netcompany',
    position: 'Talented IT Graduates',
    location: '',
    JD_link: 'https://docs.google.com/document/d/1M9Hjq8H5nSUc6G5hibDTLG3HumU-13z1/edit?usp=sharing&ouid=104119655429819847708&rtpof=true&sd=true',
    logo: require('../../images/logo_2025/Netcompany.webp'),
    },
    {
        company: 'TTI',
        position: 'Data Engineer Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/175vokCv5TD2ing-UPjVZBMhvNXT2IDMg/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'FPT Software',
        position: 'Fresher SAP Functional Consultant (German/French)',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1B-ijLygA_Of3dn5x4uHdJx133ZA2_r2L/edit?usp=drive_link&ouid=107987931277148505499&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/FPT Software.webp'),
    },
  ];