export const engineeringJobs = [
    {
        company: 'TTI',
        position: 'Quality Management & Lab Interns',
        location: '',
        JD_link: 'https://drive.google.com/drive/folders/1d0fA8dUPPOkiGuE9ol4vdejSSlfpa-xr?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'TTI',
        position: 'Value Engineering Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1ni3XKWrUyzND79IV6MeMp0-lcc89kiiV/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'Kyungbang',
        position: 'Maintenance Staff',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1h4AYZZvzTDbLWK2WXadMiCk8BfczBfAJ/edit?usp=drive_link&ouid=114794095987303658186&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/Kyungbang.webp'),
    },
    {
        company: 'Kyungbang',
        position: 'Electrical Technician',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1h4AYZZvzTDbLWK2WXadMiCk8BfczBfAJ/edit?usp=drive_link&ouid=114794095987303658186&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/Kyungbang.webp'),
    },
    {
        company: 'KyungBang',
        position: 'Mechanical Technician',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1RCjnDqSpMuw_0a9_YEqONXRouvArHzb2/edit?usp=drive_link&ouid=114794095987303658186&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/Kyungbang.webp'),
    },
    {
        company: 'fischer',
        position: 'Supplier Quality Engineer',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1SiqWd44pwZXgcyvxWNaRKmo-WPJthN9b/edit?usp=drive_link&ouid=102380696678556884167&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/fischer.webp'),
    },
    {
        company: 'MAC ZT',
        position: 'BIM Engineer - Allplan',
        location: '',
        JD_link: 'https://www.topcv.vn/viec-lam/bim-engineer-ky-su-trien-khai-ban-ve-allplan/1706254.html?t...46510265',
        logo: require('../../images/logo_2025/MAC ZT.webp'),
    },
    {
        company: 'MAC ZT',
        position: 'QA Engineer',
        location: '',
        JD_link: 'https://www.topcv.vn/viec-lam/qa-engineer-ky-su-kiem-tra-chat-luong/1716734.html?ta_source=JobSearchList_LinkDetail&u_sr_id=kwaMSSjWFL4BFZLMivBH1YOgroEEHuHJjXPb0XNq_1746510265',
        logo: require('../../images/logo_2025/MAC ZT.webp'),
    },
    {
        company: 'LEGO',
        position: 'Technical Trainer for Automated Warehouse',
        location: '',
        JD_link: 'https://www.lego.com/en-us/careers/job/technical-trainer-for-automated-warehouse-0ae77488d3591001072c7681f1980000',
        logo: require('../../images/logo_2025/LEGO.webp'),
    },
    {
        company: 'LEGO',
        position: 'Technical Writer for Automated Warehouse',
        location: '',
        JD_link: 'https://www.lego.com/en-us/careers/job/technical-writer-for-automated-warehouse-53066e37077b100107321452e94c0000',
        logo: require('../../images/logo_2025/LEGO.webp'),
    },
    {
        company: 'LEGO',
        position: 'Maintenance Technician (Automated Warehouse)',
        location: '',
        JD_link: 'https://www.lego.com/en-us/careers/job/maintenance-technician-automated-warehouse-0ae77488d359100107432d47a6930000',
        logo: require('../../images/logo_2025/LEGO.webp'),
    },
    {
        company: 'Nextern',
        position: 'IPQC Engineer',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1QYmQ8cEqH_PT1s5sPdPvxIJhJ8kKpoVH/view?usp=drive_link',
        logo: require('../../images/logo_2025/nextern.webp'),
    },
    {
        company: 'Wanek',
        position: 'Warehouse Automation Design Engineer',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1T1FQe2zEufYXK53lJongo5GYsU9yLjMk/edit',
        logo: require('../../images/logo_2025/wanek.webp'),
    },
    {
        company: 'Wanek',
        position: 'PLC & Robotic Programmer',
        location: '',
        JD_link: 'https://docs.google.com/document/d/17C9arb3CKXDTocXvXebWkOi7fLek0EyT/edit',
        logo: require('../../images/logo_2025/wanek.webp'),
    },
    {
        company: 'Wanek',
        position: 'Automation Design Engineer',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1woloLCZDy4LZhFm_FU0XTzKAb3ngjGar/edit?usp=drive_web&ouid=113519301845794276564&rtpof=true',
        logo: require('../../images/logo_2025/wanek.webp'),
    },
    {
        company: 'Indefol',
        position: 'Mechanical Engineer Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1Z7fnt3QDPDKp_twCJzedIN2CJuvhdnJD/view?usp=drive_open',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'Indefol',
        position: 'Quality Management Engineering Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1bosarfvCa9jp24t1QoUGgUeb0WsYnGDn/view?usp=drive_open',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'Indefol',
        position: 'Automation Electrical Engineer',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1-aW4L18vdTq8SJBBadB8XO-UpTrXqhwr/view?usp=drive_link',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'Indefol',
        position: 'Mechanical Engineer',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1uv50Wxt8ZwlP_lgD5VwZntwXVDBYz50N/view?usp=drive_link',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'Indefol',
        position: 'Quality Management Engineer',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1Y7eukgMP4R2rZM4PGyHvrnfpNbHECBV4/view?usp=drive_link',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'MAC ZT',
        position: 'MEP Engineer - HVAC Modeler',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1YcOw6Z6-rIKwMXyprdCDaA-_N8G__5O2/edit?usp=drive_link&ouid=107987931277148505499&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/MAC ZT.webp'),
    },
    {
        company: 'MAC ZT',
        position: 'MEP Engineer - Sanitary Modeler',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1B-ijLygA_Of3dn5x4uHdJx133ZA2_r2L/edit?usp=drive_link&ouid=107987931277148505499&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/MAC ZT.webp'),
    },
    {
        company: 'FPT Software',
        position: 'Fresher SAP Functional Consultant (German/French)',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1YYwqy7RVgYGR4KhSMpPORM5Wa5Vb8YNw/view?usp=sharing',
        logo: require('../../images/logo_2025/FPT Software.webp'),
    },
    {
        company: 'Ziehl Abegg',
        position: 'HSE (Health, Safety, and Environment) Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1W5lvk2Mx3LKBPJVcyFcpLXfui5R428P4/view?usp=drive_link',
        logo: require('../../images/logo_2025/Ziehl Abegg.webp'),
    },
    {
        company: 'Ziehl Abegg',
        position: 'Maintenance Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1L9_LPPHndMnc2CYZeKjIzXxDnRzPgT0u/view?usp=drive_link',
        logo: require('../../images/logo_2025/Ziehl Abegg.webp'),
    },
    {
        company: 'Ziehl Abegg',
        position: 'Manufacturing Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1qXMIcettuR20J9qn3zkwALRVlC1YJrQQ/view?usp=drive_link',
        logo: require('../../images/logo_2025/Ziehl Abegg.webp'),
    },
  ];
  
  export const econMgmtJobs = [
    {
        datacompany: 'KyungBang',
        position: 'Production Supervisor',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1dxS-jfsvGadbwYpjNGGFDObpOW73vK8v/edit?usp=drive_link&ouid=114794095987303658186&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/Kyungbang.webp'),
    },
    {
        datacompany: 'KyungBang',
        position: 'Sale Executive',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1YPr-5SgkVjc8QasUfWST4Vwhc0dhmv0s/edit?usp=drive_link&ouid=114794095987303658186&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/Kyungbang.webp'),
    },
    {
        company: 'KyungBang',
        position: 'Compliance Auditor',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1avJVPA18mIQie9jQ23-GlnBAL4663HSJ/edit?usp=drive_link&ouid=114794095987303658186&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/Kyungbang.webp'),
    },
    {
        company: 'fischer',
        position: 'Executive Purchaser',
        location: '',
        JD_link: 'https://docs.google.com/document/d/1GsJx-zQPVzeJlmT7yMtgDmfhET5Dtemt/edit?usp=drive_link&ouid=102380696678556884167&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/fischer.webp'),
    },
    {
        company: 'Shopee',
        position: 'Customer Relationship Management Associate - Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01995372/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'Shopee',
        position: 'Partnership Management Associate - SPX Express',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01995338/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'Shopee',
        position: 'Campaign Management Associate - Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01995168/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'Shopee',
        position: 'Business Product Management Associate - Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01995300/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'Shopee',
        position: 'Business Development Planning Associate - Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J02011945/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'Shopee',
        position: 'Ads Services Specialist',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J02012106/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'Shopee',
        position: 'Warehouse Admin - Operations, Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J00338971/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'Shopee',
        position: 'Quality Assurance Associate - Shopee',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01995273/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'Shopee',
        position: 'Key Account Management Associate - Shopee HCM',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01994668/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'Shopee',
        position: 'Key Account Management Associate - Shopee HN',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J01994687/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'Shopee',
        position: 'BD Admin - Business Development, ShopeeFood',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J02012398/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'Shopee',
        position: 'Recruiter - People Team, Shopee (Working location: Ha Noi & Ho Chi Minh)',
        location: '',
        JD_link: 'https://careers.shopee.vn/job-detail/J02007770/1?channel=10001',
        logo: require('../../images/logo_2025/shopee.webp'),
    },
    {
        company: 'FPT Software',
        position: 'Fresher SAP Functional Consultant (German/French)',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1YYwqy7RVgYGR4KhSMpPORM5Wa5Vb8YNw/view?usp=sharing',
        logo: require('../../images/logo_2025/FPT Software.webp'),
    },
    {
        company: 'Ziehl Abegg',
        position: 'Accountant Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1K5CS8MhVwerDDIGWn8vrA9sww43447Mz/view?usp=drive_link',
        logo: require('../../images/logo_2025/Ziehl Abegg.webp'),
    },
    {
        company: 'Ziehl Abegg',
        position: 'HR - Admin Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1TVZUcsgRP5OCGYrNCcjRzPMc9EReMNDb/view?usp=drive_link',
        logo: require('../../images/logo_2025/Ziehl Abegg.webp'),
    },
    {
        company: 'Techcombank',
        position: 'Personal Client Specialist',
        location: '',
        JD_link: 'https://www.techcombankjobs.com/job/TP_-H%E1%BB%93-Ch%C3%AD-Minh-Chuy%C3%AAn-vi%C3%AAn-Kh%C3%A1ch-h%C3%A0ng-C%C3%A1-nh%C3%A2n-%2840001007%29/19606244/',
        logo: require('../../images/logo_2025/Techcombank.webp'),
    },
    {
        company: 'Techcombank',
        position: 'Personal Client Intern',
        location: '',
        JD_link: 'https://tuyendung.techcombankjobs.com/thuc-tap-khcn',
        logo: require('../../images/logo_2025/Techcombank.webp'),
    },
  ];
  export const urbanEnvJobs = [
    {
        company: 'Mitek',
        position: 'Structural designer',
        location: '',
        JD_link: 'https://docs.google.com/spreadsheets/d/1hXNxizMhjSfS1u6keaFMc__xoRSNXFfD/edit?usp=drive_link&ouid=113519301845794276564&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/mitek.webp'),
    },
    {
        company: 'Mitek',
        position: 'Architectural Drafter',
        location: '',
        JD_link: 'https://docs.google.com/spreadsheets/d/1hXNxizMhjSfS1u6keaFMc__xoRSNXFfD/edit?usp=drive_link&ouid=113519301845794276564&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/mitek.webp'),
    },
    {
        company: 'Mitek',
        position: 'Budget Officer',
        location: '',
        JD_link: 'https://docs.google.com/spreadsheets/d/1hXNxizMhjSfS1u6keaFMc__xoRSNXFfD/edit?usp=drive_link&ouid=113519301845794276564&rtpof=true&sd=true',
        logo: require('../../images/logo_2025/mitek.webp'),
    },
    {
        company: 'Indefol',
        position: 'Chemical Engineer Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1h4rRwc6mfyRUF7Vl9IBAAyZoHGRe6Pbo/view?usp=drive_open',
        logo: require('../../images/logo_2025/Indefol.webp'),
    },
    {
        company: 'FPT Software',
        position: 'Fresher SAP Functional Consultant (German/French)',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1YYwqy7RVgYGR4KhSMpPORM5Wa5Vb8YNw/view?usp=sharing',
        logo: require('../../images/logo_2025/FPT Software.webp'),
    },
  ];
  export const itJobs = [
    {
    company: 'Netcompany',
    position: 'Talented IT Graduates',
    location: '',
    JD_link: 'https://docs.google.com/document/d/1M9Hjq8H5nSUc6G5hibDTLG3HumU-13z1/edit?usp=sharing&ouid=104119655429819847708&rtpof=true&sd=true',
    logo: require('../../images/logo_2025/Netcompany.webp'),
    },
    {
        company: 'TTI',
        position: 'Data Engineer Intern',
        location: '',
        JD_link: 'https://drive.google.com/file/d/175vokCv5TD2ing-UPjVZBMhvNXT2IDMg/view?usp=drive_link',
        logo: require('../../images/logo_2025/TTI.webp'),
    },
    {
        company: 'FPT Software',
        position: 'Fresher SAP Functional Consultant (German/French)',
        location: '',
        JD_link: 'https://drive.google.com/file/d/1YYwqy7RVgYGR4KhSMpPORM5Wa5Vb8YNw/view?usp=sharing',
        logo: require('../../images/logo_2025/FPT Software.webp'),
    },
  ];